name: Security checks (dogfooding)

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  brakeman:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby 4.0.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.1
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Brakeman report
        run: |
          bundle exec brakeman -A -q --force -f json -o tmp/${{ github.event.pull_request.head.sha }}-brakeman.json
      - name: Send Brakeman report to Github if it has warnings
        if: failure()
        uses: cookpad/brakeman-linter-action@v2.3.0-rc.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPORT_PATH: tmp/${{ github.event.pull_request.head.sha }}-brakeman.json
          GITHUB_LATEST_SHA: ${{ github.event.pull_request.head.sha }}
          CUSTOM_MESSAGE_CONTENT: "Please address this issue before merging.<br />Thank you for improving our security!"
