name: Style checks

on:
  push:
    branches:
      - main

jobs:
  rubocop:
    name: Rubocop Action
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.7.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run Rubocop
        run: rubocop

