name: Style checks

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  rubocop:
    name: Rubocop Action
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby 4.0.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.1
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run Rubocop
        run: bundle exec rubocop

