name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Rspec Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.7.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run Rspec
        run: rspec
