name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

permissions:
  contents: read

jobs:
  test:
    name: Rspec Test Action
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.7.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run Rspec
        run: rspec
